version: '3.1'

services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/postgresql/Dockerfile
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - DEBUG=true
      - PG_TRUST_LOCALNET=true
      - DB_EXTENSION=uuid-ossp
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
      - POSTGRES_MULTIPLE_DATABASES=gostack_gobarber
    volumes:
      - /Users/feliperochaoliveira/Documents/projects/gobarber-server/src/database:/var/lib/postgresql

  # Use root/example as user/password credentials
  mongo:
    image: bitnami/mongodb:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: docker
      MONGO_INITDB_DATABASE: gostack_gobarber

  redis:
    image: bitnami/redis:latest
    container_name: cache
    expose:
      - 6379

  app:
    # some definitions
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache
      # rest of the environment definitions
