version: '3.1'

services:
  postgres:
    image: 'bitnami/postgresql:latest'
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_DATABASE=gostack_gobarber
    volumes:
      - ~/app/gobarber/src/database:/bitnami/postgresql

  # Use root/example as user/password credentials
  mongodb:
    image: bitnami/mongodb:latest
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      - MONGODB_USERNAME=mongo
      - MONGODB_PASSWORD=docker
      - MONGODB_DATABASE=gostack_gobarber

  redis:
    image: bitnami/redis:latest
    container_name: redis
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=docker
